---
  - name : ansible palaybook for docker
    hosts : 
      - 172.31.92.138
    become : true
    connection : ssh
    tasks :
      - name : package update
        command : apt update
      - name : jdk install
        command : apt install default-jdk -y
      - name : docker imstall
        command : apt install docker.io -y
      - name : docker container create
        command : docker run -d -p 9090:8080 --name app01 soumyaranjanrout0/project5
